/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class media_ushow_aac_codec_fdk_AACEncoder */

#ifndef _Included_media_ushow_aac_codec_fdk_AACEncoder
#define _Included_media_ushow_aac_codec_fdk_AACEncoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     media_ushow_aac_codec_fdk_AACEncoder
 * Method:    encode
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_media_ushow_aac_1codec_1fdk_AACEncoder_encode
  (JNIEnv *, jobject, jstring, jstring);

JNIEXPORT jint JNICALL Java_media_ushow_aac_1codec_1fdk_AACEncoder_encodeAndDecodeTest
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
